version: '3.5'

services:
  frontend:
      ports:  
        - 3000:3000
      build: ./ml-kurkkumopo-frontend
      environment:
        - API_URL=http://localhost:5000 
      container_name: frontend2.7
  backend:
      build: ./ml-kurkkumopo-backend
      volumes:
        - model:/src/model
      container_name: backend2.7
  training:
      build: ./ml-kurkkumopo-training
      volumes: 
        - model:/src/model
        - ./imgs:/src/imgs
        - ./data:/src/data
      container_name: training2.7

volumes:
  model:
